// TodoList-Vue/src/app/views/Todo/index.vue
<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { mapState, mapMutations } from 'vuex'

@Component({ computed: mapState(['list']), methods: mapMutations(['DELETE_ITEM', 'CHANGE_STATE']) })
class Todo extends Vue {
  // 删除item
  handleClick(id: number) {
    (this as any).DELETE_ITEM(id)
  }
  
  handleChange(id: number) {
    (this as any).CHANGE_STATE(id)
  }
}

export default Todo
</script>

<template>
  <div class="list">
    <div class="list-item" v-for="item in this.list.filter(item => item.isDone === false)" :key="item.id">
      <div class="content">
        <input type="checkbox" :checked="item.isDone" @change="() => handleChange(item.id)">
        <span :class="item.isDone && 'isdone'">{{ item.content }}</span>
      </div>
      <div><button @click="() => handleClick(item.id)">删除</button></div>
    </div>
  </div>
</template>

<style lang="scss">
.list {
  .list-item {
    display: flex;
    margin: 5px 0;
    .content {
      flex: 1;
    }
    .isdone {
      text-decoration: line-through;
      color: #ccc;
    }
  }
}
</style>

// TodoList-React/src/Views/Todo/Todo.jsx
import React from "react";
import { connect } from "react-redux";
import PropTypes from 'prop-types';

const TodoUI = (props) => {
  
  const handleChange = (id) => {
    props.CHANGE_STATE(id);
  }
  
  const handleClick = (id) => {
    props.CHANGE_STATE(id);
  }
  
  return (
    <>
      <ul>
        {
          props.list.filter(data => 
            data.isDone === false
          ).map(item=>{
            return(
              <li key={ item.id } className={item.isDone ? "isdone" : ""}>
                <div className="box_content">
                  <div><input type="checkbox" checked={ item.isDone } onChange={ () => handleChange(item.id) }/></div>
                  <div>{ item.content }</div>
                </div>
                <div><button onClick={ () => handleClick(item.id) }>删除</button></div>
              </li>
            )
          })
        }
      </ul>
      
    </>
  )
};

const mapStateToProps = (state) => {
  return {
    list: state.list
  };
}

const mapDispatchToProps = (dispatch) => {
  return {
    CHANGE_STATE: id => dispatch({ type: "CHANGE_STATE", payload: id }),
    DELETE_LIST: id => dispatch({ type: "DELETE_LIST", payload: id }),
  }
}
 
const Todo = connect( mapStateToProps, mapDispatchToProps )( TodoUI );

TodoUI.propTypes = {
  list: PropTypes.array
};

export default Todo;
